CREATE TABLE users (
	id INT PRIMARY KEY,
    email VARCHAR(255),
    password VARCHAR(255),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE users
MODIFY email VARCHAR(255) NOT NULL;

ALTER TABLE users
MODIFY password VARCHAR(255) NOT NULL;